# Generated by Django 4.2.6 on 2023-10-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartcontract',
            name='contract',
            field=models.CharField(max_length=500),
        ),
    ]
